### ISSUE TITLE
Add osx-arm64 build

### ISSUE THREAD

**Issue by tomwhite** [conda-forge/bed-reader-feedstock#6]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

This is needed to install on a M1 Mac Mini. There are some instructions here: https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock. It looks like conda-forge-pinning should be updated to start with?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : sgkit-dev-3.8
    active env location : /opt/homebrew/Caskroom/miniforge/base/envs/sgkit-dev-3.8
            shell level : 2
       user config file : /Users/tom/.condarc
 populated config files : /opt/homebrew/Caskroom/miniforge/base/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.6.final.0
       virtual packages : __osx=11.5.2=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /opt/homebrew/Caskroom/miniforge/base  (writable)
      conda av data dir : /opt/homebrew/Caskroom/miniforge/base/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/homebrew/Caskroom/miniforge/base/pkgs
                          /Users/tom/.conda/pkgs
       envs directories : /opt/homebrew/Caskroom/miniforge/base/envs
                          /Users/tom/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.6 Darwin/20.6.0 OSX/11.5.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

**Comment by jeromekelleher** [comment]
Thanks @tomwhite - I'll see if I can get this working for tskit first, and then loop back here once I understand the process.

**Comment by tomwhite** [comment]
@jeromekelleher @CarlKCarlK do you have any sense of how much work this would be to get conda packages for OSX arm64? In sgkit, we are down to bed-reader and cbgen (https://github.com/conda-forge/cbgen-feedstock/issues/6) being the remaining dependencies that need to be built for the new hardware.

**Comment by CarlKCarlK** [comment]
Tom,

I’ll take a stab at the very first step: trying to get bed-reader to use GitHub actions and build on OSX arm64.

@horta is the dev and lead on cbgen, so you'll likely want to include him in on this question.

**Comment by CarlKCarlK** [comment]
Tom,

(I now see that @horta is already involved.) It doesn't look like Github Actions currently supports ARM. So, that means I don't really know how to test even a basic build and test for ARM.

bed-reader uses Rust and Python. I had a hope that it would "just work" on ARM. Is that not the case? (I don't know much about Feedstock, so if you can point me to error messages, they would be interesting to me.

- Carl

**Comment by tomwhite** [comment]
Hi Carl - thanks for taking a look at this!

For cbgen I issued a PR here https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2070 following the instructions https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock, but I rapidly reached the extent of my conda-forge knowledge! @horta said he would have a look at doing what's needed to build cbgen for macos arm64 (https://github.com/conda-forge/cbgen-feedstock/issues/6).

For bed-reader I'd be happy to submit a PR to the conda-forge-pinning-feedstock repo, but its the parts after that step that are unclear. I have a Mac Mini with an M1 chip that I can test binaries on if that helps at any point.

Thanks, Tom

**Comment by CarlKCarlK** [comment]
Tom,
As far as I know, no one has ever compiled, tested, or run bed-reader on an M1. It would be great if you could try and report back any problems. Here are the steps (based on https://github.com/fastlmm/bed-reader/blob/master/.github/workflows/ci.yml, tested on Ubuntu under Windows):

```
# based on https://github.com/fastlmm/bed-reader/blob/master/.github/workflows/ci.yml

# Assumes Python 3.7, 3.8 or 3.9 installed

# Get bed-reader
git clone https://github.com/fastlmm/bed-reader.git bed_reader
cd bed_reader

# Install flake8, etc
python -m pip install --upgrade pip
pip install flake8 pytest black isort --upgrade

# Lint with flake8, etc
echo "flake8"
flake8 .
echo "black"
black --version
black --verbose --check .
echo "isort"
isort --check-only .

# Set up Rust
# see https://rustup.rs/ for details
curl https://sh.rustup.rs -sSf | sh -s -- -y
source $HOME/.cargo/env

# Install Maturin (Rust library for Python)
python -m pip install --upgrade pip maturin

# Test Rust
cargo test --verbose

# Build wheel with Maturin - Non-Linux
maturin list-python
maturin build --release
ls -las target/wheels
cp target/wheels/*.whl .

# Test Python
pip install virtualenv
virtualenv vEnv; vEnv\Scripts\activate.ps1
echo "pwd"
pwd
python -m pip install --upgrade pip maturin
echo "requirements"
pip install -r requirements.txt
echo "requirements-dev"
pip install -r requirements-dev.txt
echo "maturin"
maturin develop
echo "numpy"
pip install numpy
echo "pytest"
pytest bed_reader

**Comment by jeromekelleher** [comment]
Building the wheels for arm was actually pretty straightforward @tomwhite, I can try the same approach here, probably.

We should get the current build fixed first though - #5 is still open @CarlKCarlK , did you ever get around to figuring out what was going on there/

**Comment by tomwhite** [comment]
Thanks for the instructions @CarlKCarlK. Sounds like @jeromekelleher can try to build the binaries using the same approach as msprime/tskit.

**Comment by jeromekelleher** [comment]
Should be @tomwhite, although the interaction with Rust is an unknown here.

**Comment by tomwhite** [comment]
Any chance of looking at this again @CarlKCarlK and @jeromekelleher now that #5 is fixed?

**Comment by CarlKCarlK** [comment]
Hi

I think I tested the script that I gave in the issue thread on an M1 Mini and it worked. (I think I used scaleway.com and do seem to have an account there.)

So, as far as I know bed-reader should work fine on an M1. I don't really know anything about conda-forge. Is there a way to see if it works now?


  *   Carl

**Comment by jeromekelleher** [comment]
I can take a look, but it'll be a few weeks before I can get to it I'm afraid

**Comment by tomwhite** [comment]
Thanks @CarlKCarlK and @jeromekelleher

**Comment by CarlKCarlK** [comment]
There is a new version of bed-reader. It updates some settings to work better with the current version maturin (the Rust to Python library). I just retested the script given above (https://github.com/conda-forge/bed-reader-feedstock/issues/6#issuecomment-954843673). The script still works to build on Linux (and I assume MacOS).

**Comment by jeromekelleher** [comment]
It turns out that all the builds were broken (#20) which I fixed in #19.

I had a go at adding OSX ARM over in #18, but hit against some new issues, some of which look at a bit ominous in terms of available package versions: 

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=569001&view=logs&j=385a3385-ae8b-54d1-9abe-3c614f74cb73&t=a5f9d343-149e-5621-6ab9-f0278009be04&l=89

**Comment by CarlKCarlK** [comment]
Jerome,

I think this is a summary of the current status (please correct me if wrong)


  *   All the Windows builds fail with "input line is too long".
(This discussion might be helpful: https://stackoverflow.com/questions/34818282/anaconda-prompt-loading-error-the-input-line-is-too-long/35439610)

  *   Some OSX Arm builds fail, but other don't. The error message says: requires python_abi 3.10

When I look at https://anaconda.org/vpython/python_abi/files I see files for ARM for every version of Python, so the error seems weird.


  *   Carl

**Comment by jeromekelleher** [comment]
That's about it @CarlKCarlK. The windows failures are weird, because they're actually building fine in main and this update to add OSX ARM shouldn't have had any effect.

Probably the only way to workaround the lack of the right version of maturin is to put in some skips for the affected Python versions.

**Comment by CarlKCarlK** [comment]
FYI:

I just released bed-reader 0.2.29. It fixes a spontaneous MacOS build problem on GitHub Actions.

There is a small chance that this version will help Conda Forge.


  *   Carl


p.s. Details:

A GitHub action that previously worked, stopped working on MacOS x64. This fixed it:

From the Rust extensions for Python manual Building and Distribution - PyO3 user guide<https://pyo3.rs/v0.14.4/building_and_distribution.html#macos>:
On macOS, because the extension-module feature disables linking to libpython (see the next section<https://pyo3.rs/v0.14.4/building_and_distribution.html#the-extension-module-feature>), some additional linker arguments need to be set. maturin and setuptools-rust both pass these arguments for PyO3 automatically, but projects using manual builds will need to set these directly in order to support macOS.
The easiest way to set the correct linker arguments is to add a build.rs<https://doc.rust-lang.org/cargo/reference/build-scripts.html> with the following content:
fn main() {
  pyo3_build_config::add_extension_module_link_args();
}

**Comment by tomwhite** [comment]
Not sure what the state of the this is, but it would still be great to get it working

**Comment by CarlKCarlK** [comment]
I'm traveling but will be able to work on the PyPi part of this within the next 7 days. -Carl
________________________________

**Comment by CarlKCarlK** [comment]
The PyPi version of bed-reader is working on osx-arm64. I don't know how/what to do for conda.

**Comment by horta** [comment]
Is it worth having it on conda-forge? Because all my python projects now compile wheels using Github actions and cibuildwheels and then it becomes a matter of `pip install package`. I was using conda-forge in the past because cibuildwheels didn't exist or was not as well-known/supported as today.

**Comment by tomwhite** [comment]
Some groups still prefer not to depend on pip packages, so I think having conda packages is important.

@jeromekelleher got osx-arm64 packages working for [tskit](https://anaconda.org/conda-forge/tskit), which I believe has a non-trivial build system too, and he created #18 a while back to do the same thing here. Maybe that can be retried now the build here is working again? (BTW it looks like #29 can be merged?)

**Comment by jeromekelleher** [comment]
The interaction with Rust is an unknown for me here @tomwhite - but yeah, it's worth trying again when the package updates are done in #29
